import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET() {
  const session = await auth();
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const triggers = await prisma.templateAutoTrigger.findMany({ orderBy: { workflowTag: "asc" } });
  const pending = await prisma.autoGeneratedTemplate.findMany({ where: { status: "pending_review" }, orderBy: { createdAt: "desc" }, take: 20 });

  return NextResponse.json({ triggers, pendingReview: pending });
}

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const role = (session.user as any).role;
  if (!["super_admin", "admin"].includes(role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { workflowTag, templateType, styleId, enabled } = await req.json();
  if (!workflowTag || !templateType) return NextResponse.json({ error: "workflowTag and templateType required" }, { status: 400 });

  const trigger = await prisma.templateAutoTrigger.upsert({
    where: { workflowTag },
    update: { templateType, styleId, enabled: enabled !== false },
    create: { workflowTag, templateType, styleId, enabled: enabled !== false },
  });
  return NextResponse.json(trigger, { status: 201 });
}
