import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const role = (session.user as any).role;
  if (!["super_admin", "admin"].includes(role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { id } = await params;
  const { action, reviewNote } = await req.json();
  if (!["approved", "rejected"].includes(action)) return NextResponse.json({ error: "action must be approved or rejected" }, { status: 400 });

  const auto = await prisma.autoGeneratedTemplate.findUnique({ where: { id } });
  if (!auto) return NextResponse.json({ error: "Not found" }, { status: 404 });

  await prisma.autoGeneratedTemplate.update({
    where: { id },
    data: { status: action, reviewedBy: session.user.id, reviewedAt: new Date(), reviewNote },
  });

  if (action === "approved") {
    if (auto.templateType === "email" && auto.bodyHtml) {
      await prisma.emailTemplate.create({
        data: {
          key: `auto_${auto.workflowTag}_${Date.now()}`,
          name: auto.name,
          subject: auto.subject || auto.name,
          heading: auto.name,
          bodyHtml: auto.bodyHtml,
          bodyText: auto.bodyText || "",
          category: "Auto Generated",
          status: "active",
          workflowTags: [auto.workflowTag],
          aiGenerated: true,
          generationPrompt: `Auto-generated for ${auto.workflowTag}`,
        },
      });
    } else if (auto.smsBody) {
      await prisma.smsTemplate.create({
        data: {
          key: `auto_sms_${auto.workflowTag}_${Date.now()}`,
          name: auto.name,
          body: auto.smsBody,
          category: "Auto Generated",
          status: "active",
          characterCount: auto.smsBody.length,
          segmentCount: auto.smsBody.length <= 160 ? 1 : Math.ceil(auto.smsBody.length / 153),
          workflowTags: [auto.workflowTag],
          aiGenerated: true,
          generationPrompt: `Auto-generated for ${auto.workflowTag}`,
        },
      });
    }

    await prisma.templateAutoTrigger.update({
      where: { workflowTag: auto.workflowTag },
      data: { approvedCount: { increment: 1 } },
    });
  } else {
    await prisma.templateAutoTrigger.update({
      where: { workflowTag: auto.workflowTag },
      data: { rejectedCount: { increment: 1 } },
    });
  }

  return NextResponse.json({ ok: true, status: action });
}
