import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { generateEmailTemplate, generateSmsTemplate } from "@/lib/ai/templateGenerator";

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const role = (session.user as any).role;
  if (!["super_admin", "admin"].includes(role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { workflowTag } = await req.json();
  if (!workflowTag) return NextResponse.json({ error: "workflowTag required" }, { status: 400 });

  const trigger = await prisma.templateAutoTrigger.findUnique({ where: { workflowTag } });
  if (!trigger || !trigger.enabled) return NextResponse.json({ error: "No active trigger for this workflow" }, { status: 404 });

  const existingActive = trigger.templateType === "email"
    ? await prisma.emailTemplate.findFirst({ where: { workflowTags: { has: workflowTag }, status: "active" } })
    : await prisma.smsTemplate.findFirst({ where: { workflowTags: { has: workflowTag }, status: "active" } });

  if (existingActive) return NextResponse.json({ message: "Active template already exists", templateId: existingActive.id });

  const vars = await prisma.templateVariable.findMany();
  const action = await prisma.workflowAction.findUnique({ where: { tag: workflowTag } });
  const prompt = `Generate a ${trigger.templateType} template for the "${action?.name || workflowTag}" workflow action. ${action?.description || ""}`;

  let generated: any;
  if (trigger.templateType === "email") {
    generated = await generateEmailTemplate({ userPrompt: prompt, styleId: trigger.styleId || "", availableVariables: vars });
  } else {
    generated = await generateSmsTemplate({ userPrompt: prompt, styleId: trigger.styleId || "", availableVariables: vars, enforceCharLimit: true });
  }

  const auto = await prisma.autoGeneratedTemplate.create({
    data: {
      triggerId: trigger.id,
      workflowTag,
      templateType: trigger.templateType,
      name: generated.name,
      subject: generated.subject || null,
      bodyHtml: generated.bodyHtml || null,
      bodyText: generated.bodyText || null,
      smsBody: generated.body || null,
      styleUsed: trigger.styleId,
      status: "pending_review",
    },
  });

  await prisma.templateAutoTrigger.update({ where: { workflowTag }, data: { lastTriggeredAt: new Date(), generatedCount: { increment: 1 } } });

  return NextResponse.json(auto, { status: 201 });
}
